[package]
name = "ssahindb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "ssahindb-cli"
path = "src/cli.rs"

[[bin]]
name = "example-rs"
path = "libraries/rust/example.rs"
